- hosts: 10.0.0.4
  become: true
  tasks:
   - name: delete old deployment
     command: kubectl delete --kubeconfig=/home/ubuntu/.kube/config -f /home/ubuntu/Deployment.yml
   - name: delete old service
     command: kubectl delete --kubeconfig=/home/ubuntu/.kube/config -f /home/ubuntu/Service.yml
   - name: create new deployment
     command: kubectl apply --kubeconfig=/home/ubuntu/.kube/config -f /home/ubuntu/Deployment.yml
   - name: create new service
     command: kubectl apply --kubeconfig=/home/ubuntu/.kube/config -f /home/ubuntu/Service.yml
